services:
  db:
    image: postgres:latest
    restart: always
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    ports:
      - '${NEST_APP_PORT}:3000'
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: ['npm', 'run', 'start:dev']

volumes:
  pgdata:
